#!/bin/bash
#SBATCH --account=IscrB_ProAmmo
#SBATCH --time 12:00:00             # format: HH:MM:SS
#SBATCH --nodes=1                   # node
#SBATCH --ntasks-per-node=4         # tasks out of 32
#SBATCH --gres=gpu:4                # gpus per node out of 4
#SBATCH --cpus-per-task=8
#SBATCH -p boost_usr_prod
##SBATCH --qos=boost_qos_dbg 
#SBATCH --export=NONE
#SBATCH --job-name='Franken_train_multiple_pot'
############################

# source env
source ~/.bashrc

# Activate the Franken environment
# Make sure to set the correct path to your Franken environment

ENV_PATH="/leonardo/pub/userexternal/mbianchi/Franken/Franken_v0.4.0"  # Example path, change it accordingly
mamba activate "$ENV_PATH"

export OMP_NUM_THREADS=${SLURM_CPUS_PER_TASK}

#Start training at different potentials

# Define here the number of Random Features (RF) to be used for the training

for V in V_CASES;
do
    for RF in RF_CASES;
    do
        echo "Training at potential $V V with $RF Random Features"
        torchrun --standalone --nnodes=1 --nproc-per-node=4 run_train_Franken_API.py  --Potential_value  $V  --RF_number $RF 
    done
done